version: '3.8'

networks:
  td2.net:
    driver: bridge

services:
  postgres:
    image: 'postgres:latest'
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - td2.net

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - td2.net

volumes:
  postgres_data:
