version: '3.8'

networks:
  td1.net:
    driver: bridge

services:
  postgres:
    image: 'postgres:latest'
    env_file: conf_td1/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - td1.net

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - td1.net

  php:
    image: php:8.1-cli
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/TD1
    networks:
      - td1.net
    depends_on:
      - postgres

volumes:
  postgres_data:
