version: "3.8"

networks:
  catamongo.net:
    driver: bridge

services:
  php:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    ports:
      - "12080:80"
      - "12443:443"
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - catamongo.net
    command: php -S 0.0.0.0:80 -t /var/php/public

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/var/data
    working_dir: /var/data
    networks:
      - catamongo.net
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}

  mongo-express:
    image: mongo-express:latest
    networks:
      - catamongo.net
    ports:
      - "8081:8081"
    env_file:
      - .env
